### ISSUE TITLE
Great work! What is the training time for the distillation stage?

### ISSUE THREAD

**Issue by ankanbhunia** [GeorgeCazenavette/mtt-distillation#1]
Can you please tell the training time on ImageNet for the distillation exps?

**Comment by GeorgeCazenavette** [comment]
Thanks! Glad you like it :)

For ImageNet, we did not do any hyperparameter search, so all of the experiments were run with 
```
--syn_steps=20 --expert_epochs=2 --max_start_epoch=10 --lr_img=100000 --lr_lr=1e-06 --lr_teacher=0.01
```
For 10 images per class, we also used ```--batch_syn=20```.

For both 1 and 10 images per class, 5k distillation steps (while evaluating on  5 models every 1k steps) takes about 2 hours ± 20 mins on our rtx3090 GPUs. The 1 image per class experiment can fit on 1 GPU, but the 10 images per class experiment just barely needs a second. Slightly lowering ```--syn_steps``` or ```--batch_syn``` should help it fit on a single GPU if needed.

If you're mainly focused on getting some visual results, you can speed up the distillation script by increasing ```--eval_it``` (how often we evaluate) and decreasing ```--num_eval``` (number of evaluation models).

Let me know if you have any other questions!

**Comment by ankanbhunia** [comment]
Thanks for your reply.
