### ISSUE TITLE
Unrolled optimization

### ISSUE THREAD

**Issue by vadimkantorov** [GeorgeCazenavette/mtt-distillation#17]
Hi!

Do I understand correctly that the grand loss at the end will backprop through grad of grad of grad, e.g. not double backward but 20th order backward? 

I.e. student_params[5] depends on student_params[4] and grad(loss(target; student_params[4]) and same goes further and we'll have in the computation branch a path that goes through all 5 grad computations

**Comment by GeorgeCazenavette** [comment]
Hi!

I think your intuition is correct, but it's a pretty confusing thing to put into words in general.

So here's a _very rough_ sketch of the forward graph:

![image](https://user-images.githubusercontent.com/18726777/187750855-0c142399-bbc5-41c7-a198-eebeab89273c.png)

Does this match what you were thinking?
