### ISSUE TITLE
how does it work on a new model arch?

### ISSUE THREAD

**Issue by jinfagang** [GeorgeCazenavette/mtt-distillation#2]
Hi, have a question:

> learn a small number of synthetic images such that a model trained on this set alone will have similar test performance as a model trained on the full real dataset.

If I using a totally different model arch train on the distilled dataset, will it also work on any arch model? The performance still same as training on original dataset? How?

**Comment by GeorgeCazenavette** [comment]
The ultimate goal of the "Dataset Distillation" problem is to distill a small dataset that also has perfect cross-architecture generalization.

We include a small cross-architecture study in the paper. All the datasets in this table were distilled using ConvNet and evaluated on the given architecture.

There is a drop in performance, but not complete failure. We hope that future work will help make this cross-architecture gap even smaller.

![image](https://user-images.githubusercontent.com/18726777/160315703-cfa2fd81-5bb5-4c13-81d4-eeda78ff2429.png)
