### ISSUE TITLE
GPU requirement

### ISSUE THREAD

**Issue by rave78** [GeorgeCazenavette/mtt-distillation#21]
Thanks for your great work in distilled datasets.  I was wondering to know about your hardware setup for CIFAR100, tinyImagenet, and Imagenet(subset).  How long did you need for your results (generating the experts and distillation step).

**Comment by GeorgeCazenavette** [comment]
Hello, 

I will give the approximate VRAM usage we saw for the datasets you asked about:

CIFAR100
- 1ipc: 1x 2080ti (12GB)
- 10ipc: 8x 2080ti (12GB)
- 50ipc: 2x 3090 (24GB)

TinyImageNet
- 1ipc: 4x 2080ti (12GB)
- 10ipc: 6x 2080ti (12GB)
- 50ipc: 6x 3090 (24GB), but we probably could have gotten away with 4 here, average GPU usage was ~60%

ImageNet(subset)
- 1ipc: 1x 3090 (24GB)
- 10ipc: 2x 3090 (24GB)

All this being said, a recent paper actually brings the memory usage w.r.t. the number of inner loop updates from linear to constant, so the memory requirements are a lot lower now: https://arxiv.org/abs/2211.10586

They include code in the supplement of the linked ICLR submission. It directly builds off of our code with just a few changes.

As for time, this varied largely with the type of GPU and the number of inner loops.

For large datasets, evaluation takes a long time, so I would recommend lowering the frequency at which you do the evaluation. 

But in general, all the distillation experiments took no more than 5 hours with the shortest ones being around 1 hour.

Generating the expert trajectories takes a good amount of time, but you can reduce this by lowing the number of epochs you train them for. 

You only need to train up to the maximum epoch you actually plan on using at distillation time.

You can also run the buffer script multiple times on different GPUs to speed it up. The checkpoints _shouldn't_ overwrite each other unless the scripts are synced very closely, so just give a few seconds before launching duplicate jobs.

Hope this helps! Please let me know if you have any more questions.

**Comment by rave78** [comment]
thanks for the explanation
