### ISSUE TITLE
Question about imagenette

### ISSUE THREAD

**Issue by yaolu-zjut** [GeorgeCazenavette/mtt-distillation#22]
Hello, I am very interested in MTT. When I use your code about imagenette, I find it is different from the original imagenette, am I right? 

See imagenette in https://github.com/fastai/imagenette

**Comment by GeorgeCazenavette** [comment]
Ah yes, it is different on their repo.

We used the same train and validation splits as defined by the original ImageNet dataset.

FastAI originally did it this way as well, but at some point they released a new version of the splits.

See here: https://github.com/fastai/imagenette/blob/master/README.md?plain=1#L13

Sorry for any confusion, and let me know if I can be of any more help!
