### ISSUE TITLE
question on Tiny imagenet ipc=50

### ISSUE THREAD

**Issue by DongyaoZhu** [GeorgeCazenavette/mtt-distillation#25]
Hello,

This is a great work! I'm trying the uploaded results [https://georgecazenavette.github.io/mtt-distillation/tensors/index.html#tensors/tiny_50](here) for ipc=50, num_classes=200 on tiny imagenet, but I found 5 .pt files of tensors of shape [2000, ...]. Are we supposed to concatenate these 5 files to form the complete ipc=50 distilled dataset?

Thanks,
Dongyao

**Comment by GeorgeCazenavette** [comment]
Yep!

This was to get around GitHub's file size limit :)

**Comment by DongyaoZhu** [comment]
Got it, thanks a lot.
