### ISSUE TITLE
What is ZCA

### ISSUE THREAD

**Issue by youdutaidi** [GeorgeCazenavette/mtt-distillation#26]
Hi, thanks for your rigorous experiment codes on mtt-distillation.

But there is an undefined abbreviation that I can't figure out.  I find an argument "--zca" and dataset with be divided into 2 classes whether or not with ZCA, and what is ZCA?

**Comment by GeorgeCazenavette** [comment]
Zero-Phase Component Analysis is a form of data normalization/whitening.

As discussed in the paper, this was used by some previous distillation methods.

See here: https://kornia.readthedocs.io/en/latest/_modules/kornia/enhance/zca.html

Hope that helps!

**Comment by youdutaidi** [comment]
> 

Thank you. It helps a lot.
