### ISSUE TITLE
details about the full real subsets of ImageNet

### ISSUE THREAD

**Issue by zeyuanyin** [GeorgeCazenavette/mtt-distillation#35]
Hi,

I am interested about your work, and you use a special dataset called subsets of ImageNet. From the rare information in the paper and this repo, I know in each subsets of ImageNet, 
- the number of class is 10
- the resolution is 112x112
- what is the number of images in each class?

**Comment by GeorgeCazenavette** [comment]
The resolution is actually 128x128 for the results in the paper.

The number of images per class is the same as in the original ImageNet. Most classes have 1300 images, but some have a few less. All classes have 50 test images.
 
Note: the original authors of Imagenette and Imagewoof released a v2 version with rebalanced train and test splits. We did not do that here.

**Comment by zeyuanyin** [comment]
@GeorgeCazenavette Thanks for your detailed reply.
