### ISSUE TITLE
args.mom in buffer.py

### ISSUE THREAD

**Issue by liuyugeng** [GeorgeCazenavette/mtt-distillation#9]
Hi, I found there is a momentum in ```teacher_optim``` named ```args.mom``` in buffer.py but I didn't find the value of it. Could you pls provide it?
Many thanks

**Comment by GeorgeCazenavette** [comment]
Just fixed it.

I left the options to set momentum and l2 regularization for you, but we used values of 0 in all our experiments.

Initial tests seemed to perform worse with non-zero values, but I didn't spend a lot of time trying to make it work.

**Comment by liuyugeng** [comment]
Thx!
